### ISSUE TITLE
new keyword not handled correctly

### ISSUE THREAD

**Issue by albertsteckermeier** [Dan1ve/ClosureInspectionsPlugin#1]
When using a statement like `new goog.ui.Dialog().show();` within a function the recommended `goog.require` is for `newgoog.ui` but should be `goog.ui.Dialog` instead.

**Comment by Dan1ve** [comment]
Interestingly, your example actually works fine. 
However, once you chain methods like this

        new goog.ui.Dialog().show().then(param => console.log("test"))

the bug you mentioned occurs.. I'll take a look!

**Comment by albertsteckermeier** [comment]
Thanks for the fix.
